[font]
size = 10

[font.bold]
# family = "Monaspace Radon"
family = "JetBrains Mono"
style = "Bold"

[font.italic]
# family = "Monaspace Radon"
family = "JetBrains Mono"
style = "Italic"

[font.normal]
# family = "Monaspace Radon"
family = "JetBrains Mono"
style = "Regular"

[window.dimensions]
columns = 60
lines = 15

[window.padding]
x = 4
y = 4

[general]
import = [
    "~/.config/alacritty/tokyonight.toml"
]
